import { FighterStats } from './types';

export const FIGHTER_ROSTER: Record<string, FighterStats> = {
  broner: {
    id: 'broner',
    name: 'Adrien Broner',
    nickname: 'Stream Host / COB',
    division: 'Pro Contender',
    health: 1100,
    maxHealth: 1100,
    moveSpeed: 1.0,
    attackMultiplier: 1.25,
    superChargeRate: 1.0,
    passiveName: 'Philly Armor',
    passiveDesc: 'Takes 15% fewer Counter Gems. Power Gems deal +30% damage.',
    superName: "Can't Play With Me Counter",
    superDesc: '600 Damage + 5-Row Solid Red Counter Drop.',
    superDamage: 600,
    counterDropPattern: ['yellow', 'yellow', 'red', 'red', 'yellow', 'yellow'],
    themeColor: '#eab308',
    secondaryColor: '#dc2626',
    accentColor: '#fbbf24'
  },
  deen: {
    id: 'deen',
    name: 'Deen The Great',
    nickname: 'Stream Host / COB',
    division: 'Lightweight Champ',
    health: 950,
    maxHealth: 950,
    moveSpeed: 1.3,
    attackMultiplier: 1.0,
    superChargeRate: 1.25,
    passiveName: 'Chain Surge',
    passiveDesc: 'Chain Multipliers scale 1.5x faster. Soft drops grant +3% Super.',
    superName: 'Misfits Combo Blitz',
    superDesc: '520 Damage + Rapid Alternating Stair Drop.',
    superDamage: 520,
    counterDropPattern: ['blue', 'blue', 'blue', 'blue', 'blue', 'blue'],
    themeColor: '#3b82f6',
    secondaryColor: '#06b6d4',
    accentColor: '#60a5fa'
  },
  ryan_garcia: {
    id: 'ryan_garcia',
    name: 'Ryan Garcia',
    nickname: 'Warehouse Guest',
    division: 'High-Flyer',
    health: 1050,
    maxHealth: 1050,
    moveSpeed: 1.4,
    attackMultiplier: 1.2,
    superChargeRate: 1.1,
    passiveName: 'KingRy Speed',
    passiveDesc: 'Fast drop speed + clearing red gems grants +15% damage burst.',
    superName: 'Flash Left Hook KO',
    superDesc: '620 Damage + KingRy Flash Cross Barrage.',
    superDamage: 620,
    counterDropPattern: ['red', 'blue', 'red', 'blue', 'red', 'blue'],
    themeColor: '#ef4444',
    secondaryColor: '#2563eb',
    accentColor: '#f87171'
  },
  ray_j: {
    id: 'ray_j',
    name: 'Ray J',
    nickname: 'Warehouse Guest',
    division: 'Content Creator',
    health: 1020,
    maxHealth: 1020,
    moveSpeed: 1.05,
    attackMultiplier: 1.1,
    superChargeRate: 1.25,
    passiveName: 'Tech Pitch',
    passiveDesc: 'Soft drops generate +2% SUPER meter and convert 1 Counter Gem.',
    superName: 'Raytroniks Overload',
    superDesc: '520 Damage + Gold/Blue Tech Grid Drop.',
    superDamage: 520,
    counterDropPattern: ['yellow', 'blue', 'yellow', 'blue', 'yellow', 'blue'],
    themeColor: '#eab308',
    secondaryColor: '#3b82f6',
    accentColor: '#fde047'
  },
  n3on: {
    id: 'n3on',
    name: 'N3ON',
    nickname: 'Stream Collaborator',
    division: 'Agitating Speedster',
    health: 900,
    maxHealth: 900,
    moveSpeed: 1.4,
    attackMultiplier: 0.95,
    superChargeRate: 1.1,
    passiveName: 'Fast Countdown',
    passiveDesc: 'Counter Gems dropped onto rival spawn with 3-turn timers instead of 5.',
    superName: 'Twitch Agitation',
    superDesc: '480 Damage + 4-Column Fast Countdown Rain.',
    superDamage: 480,
    counterDropPattern: ['green', 'green', 'yellow', 'yellow', 'green', 'green'],
    themeColor: '#22c55e',
    secondaryColor: '#eab308',
    accentColor: '#4ade80'
  },
  blueface: {
    id: 'blueface',
    name: 'Blueface',
    nickname: 'Talent Show Guest',
    division: 'Chaos Brawler',
    health: 1050,
    maxHealth: 1050,
    moveSpeed: 0.95,
    attackMultiplier: 1.35,
    superChargeRate: 0.9,
    passiveName: 'Brawl Chaos',
    passiveDesc: 'Counter Gems drop in randomized color order to confuse rival.',
    superName: 'Thotiana Knockout',
    superDesc: '580 Damage + Randomized Noise Barrage.',
    superDamage: 580,
    counterDropPattern: ['blue', 'red', 'green', 'yellow', 'blue', 'red'],
    themeColor: '#2563eb',
    secondaryColor: '#1d4ed8',
    accentColor: '#60a5fa'
  },
  chrisean_rock: {
    id: 'chrisean_rock',
    name: 'Chrisean Rock',
    nickname: 'Stream Boxing Guest',
    division: 'Chaos Brawler',
    health: 1080,
    maxHealth: 1080,
    moveSpeed: 1.1,
    attackMultiplier: 1.3,
    superChargeRate: 0.95,
    passiveName: 'Brawling Impulse',
    passiveDesc: 'Takes 10% more damage but single gem detonations deal +40% damage.',
    superName: 'South Beach Brawl',
    superDesc: '590 Damage + Heavy Front Wall Drop.',
    superDamage: 590,
    counterDropPattern: ['red', 'red', 'red', 'red', 'yellow', 'yellow'],
    themeColor: '#ec4899',
    secondaryColor: '#ef4444',
    accentColor: '#f472b6'
  },
  rampage_jackson: {
    id: 'rampage_jackson',
    name: 'Rampage Jackson',
    nickname: 'Warehouse Guest',
    division: 'Crossover Heavy',
    health: 1150,
    maxHealth: 1150,
    moveSpeed: 0.9,
    attackMultiplier: 1.4,
    superChargeRate: 0.9,
    passiveName: 'MMA Slam',
    passiveDesc: '2x2 Power Gem detonations trigger screen shake and deal +35% damage.',
    superName: 'Slam KO',
    superDesc: '640 Damage + Heavy Gold/Red Slam Barrage.',
    superDamage: 640,
    counterDropPattern: ['red', 'yellow', 'red', 'yellow', 'red', 'yellow'],
    themeColor: '#f59e0b',
    secondaryColor: '#991b1b',
    accentColor: '#fbbf24'
  },
  adin_ross: {
    id: 'adin_ross',
    name: 'Adin Ross',
    nickname: 'Kick Collab Host',
    division: 'Content Creator',
    health: 1000,
    maxHealth: 1000,
    moveSpeed: 1.1,
    attackMultiplier: 1.0,
    superChargeRate: 1.4,
    passiveName: 'Hype Cash-In',
    passiveDesc: 'Soft/Hard drops generate +2% SUPER meter per gem dropped.',
    superName: 'Brand Risk Overload',
    superDesc: '500 Damage + Gold/Red Checkerboard Barrage.',
    superDamage: 500,
    counterDropPattern: ['yellow', 'red', 'yellow', 'red', 'yellow', 'red'],
    themeColor: '#8b5cf6',
    secondaryColor: '#ef4444',
    accentColor: '#a78bfa'
  },
  charleston_white: {
    id: 'charleston_white',
    name: 'Charleston White',
    nickname: 'Stream Rant Guest',
    division: 'Reflex Technician',
    health: 940,
    maxHealth: 940,
    moveSpeed: 1.35,
    attackMultiplier: 1.15,
    superChargeRate: 1.2,
    passiveName: 'Crash Out Rant',
    passiveDesc: 'Clearing 4+ gems forces 1 row of yellow Counter Gems onto opponent.',
    superName: 'Mace & Mic Attack',
    superDesc: '510 Damage + Crash Out Rant Grid Drop.',
    superDamage: 510,
    counterDropPattern: ['yellow', 'red', 'yellow', 'red', 'yellow', 'red'],
    themeColor: '#eab308',
    secondaryColor: '#b91c1c',
    accentColor: '#fde047'
  },
  walid_sharks: {
    id: 'walid_sharks',
    name: "Deen's Stream Rival",
    nickname: 'Reflex Phenom',
    division: 'Reflex Technician',
    health: 950,
    maxHealth: 950,
    moveSpeed: 1.35,
    attackMultiplier: 1.05,
    superChargeRate: 1.2,
    passiveName: 'Reflex Counter',
    passiveDesc: 'Clearing gems while taking damage converts 1 Counter Gem into Crash Gem.',
    superName: 'Flash Counter Uppercut',
    superDesc: '510 Damage + Full Rainbow Array Drop.',
    superDamage: 510,
    counterDropPattern: ['red', 'blue', 'green', 'yellow', 'red', 'blue'],
    themeColor: '#06b6d4',
    secondaryColor: '#3b82f6',
    accentColor: '#22d3ee'
  },
  antonio_brown: {
    id: 'antonio_brown',
    name: 'Antonio Brown',
    nickname: 'Stream Guest (AB)',
    division: 'High-Flyer',
    health: 1060,
    maxHealth: 1060,
    moveSpeed: 1.2,
    attackMultiplier: 1.15,
    superChargeRate: 1.1,
    passiveName: "Business Boomin'",
    passiveDesc: 'Hard drops yield +30% score and send +1 Counter Gem.',
    superName: '84 Catch KO',
    superDesc: '560 Damage + Gold/Cyan Business Grid.',
    superDamage: 560,
    counterDropPattern: ['yellow', 'blue', 'yellow', 'blue', 'yellow', 'blue'],
    themeColor: '#eab308',
    secondaryColor: '#06b6d4',
    accentColor: '#fbbf24'
  },
  gervonta_davis: {
    id: 'gervonta_davis',
    name: 'Gervonta Davis',
    nickname: 'AB Mentee [BOSS]',
    division: 'P4P Power',
    health: 1250,
    maxHealth: 1250,
    moveSpeed: 1.1,
    attackMultiplier: 1.45,
    superChargeRate: 1.0,
    passiveName: 'Knockout Power',
    passiveDesc: '2x2 Power Gem detonations deal 3x damage and trigger screen shake.',
    superName: 'Tank Upper Cut',
    superDesc: '700 Damage + Solid Monochromatic Red Wall.',
    superDamage: 700,
    counterDropPattern: ['red', 'red', 'red', 'red', 'red', 'red'],
    themeColor: '#991b1b',
    secondaryColor: '#450a0a',
    accentColor: '#ef4444'
  },
  floyd_mayweather: {
    id: 'floyd_mayweather',
    name: 'Floyd Mayweather',
    nickname: '50-0 Legend [GRAND BOSS]',
    division: 'Grand Boss (50-0)',
    health: 1300,
    maxHealth: 1300,
    moveSpeed: 1.2,
    attackMultiplier: 1.2,
    superChargeRate: 1.1,
    passiveName: 'The Best Ever',
    passiveDesc: 'Automatically converts 2 Counter Gems into Normal Gems every 10s.',
    superName: 'TBE 50-0 Masterclass',
    superDesc: '680 Damage + Pure Gold Wall Rain.',
    superDamage: 680,
    counterDropPattern: ['yellow', 'yellow', 'yellow', 'yellow', 'yellow', 'yellow'],
    themeColor: '#d97706',
    secondaryColor: '#78350f',
    accentColor: '#fbbf24'
  }
};
